#!/bin/bash
# llvm-12 tool chain
CTPROVER_ROOT="${CTPROVER_ROOT:-/home/user/CT_Prover}"
opt-12 -enable-new-pm=0 -load "$CTPROVER_ROOT"/script/tool/removeDeadDef/luweiDelDeadDef.so -S --luweiDelDeadDef --entry-point $3 $1 > $2
