#!/bin/bash
CTPROVER_ROOT="${CTPROVER_ROOT:-/home/user/CT_Prover}"
"$CTPROVER_ROOT"/phasar/build/tools/phasar-llvm/phasar-llvm -m $1 -D ifds-taint --analysis-config --emit-text-report $2 >> $3 2>&1
# 需要三个参数 module taint config 和 输出txt